export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body style={{ margin: 0, padding: 0, overflow: 'hidden' }} suppressHydrationWarning>
                {children}
            </body>
        </html>
    )
}
